os: osx

language: node_js

addons:
  ssh_known_hosts:
    - $DEPLOY_HOST
  homebrew:
    packages:
      - proselint

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

before_script:
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - yarn build

before_cache:
  - brew cleanup

before_deploy:
  - openssl aes-256-cbc -K $encrypted_2abb10f3e80b_key -iv $encrypted_2abb10f3e80b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -r --delete-after --quiet $FILES_TO_COPY $DEPLOY_SSH_USER@$DEPLOY_HOST:$DEPLOY_PATH_TO_FILES
    - $HTACCESS_COPY
  on:
    branch: master
